name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch (or whatever branch you use)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the private repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js with the correct version (20.12.2)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm ci  # Use npm ci for a clean install of dependencies
          CI=false npm run build  # Set CI=false to prevent treating warnings as errors

      # Deploy the build to the public GitHub Pages repository
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Adjust this path to where your build output is stored
          publish_branch: gh-pages  # The branch to push the built files to
          destination_branch: gh-pages  # Set to the branch in the public repo where GitHub Pages is hosted
          user_name: 'shadyibrahim93'  # Optional: set your name for commit author
          user_email: 'shadyaziz72@gmail.com'  # Optional: set your email for commit author
          repo: shadyibrahim93/wizard-land-public  # Your public repository where GitHub Pages is hosted
